# Generated by Django 5.0.2 on 2024-04-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_images_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image/'),
        ),
    ]
